# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='download',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='git',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mods.Tag', verbose_name='Tags'),
        ),
    ]
