# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=200)),
                ('server_owner', models.CharField(max_length=200)),
                ('server_address', models.URLField()),
                ('server_description', models.TextField()),
            ],
        ),
    ]
