# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
