# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
