# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('servers', '0002_server_server_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_address',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_description',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_owner',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_votes',
        ),
        migrations.AddField(
            model_name='server',
            name='address',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mt_version',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='server',
            name='tags',
            field=models.ManyToManyField(to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='server',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
